#!/bin/sh

screenshot="/tmp/Screenshot $(date "+%Y.%m.%d at %H:%M").png"
maim -s "${screenshot}"
xclip -selection clipboard -t image/png < "${screenshot}"
notify-send -i "${screenshot}" -u normal -a screenshot "Screenshot saved in clipboard"
